### ISSUE TITLE
Add support for battlemetrics.com

### ISSUE THREAD

**Issue by cwizard** [kennethrisa/discord-rustserverstatus#15]
const is_online = server.data.attributes.status;
        if(is_online == "online") {
          const players = server.data.attributes.players;
          const maxplayers = server.data.attributes.maxPlayers;

This is the relevant code to add support for battlemetrics, i just made it apiSite == 3 to work

**Comment by kennethrisa** [comment]
Added battlemetrics support: https://github.com/kennethrisa/discord-rustserverstatus/commit/763cc4c566dc0414cecaa6323f6fc6dd41ccdae7
