### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by ahmadalhamid** [kennethrisa/discord-rustserverstatus#19]
![2](https://user-images.githubusercontent.com/35183023/51331135-4e633400-1a79-11e9-8d57-edfa5c7b466c.PNG)

I did follow all the steps and downloaded all the modules

**Comment by kennethrisa** [comment]
Can you run command: npm list -depth 0

You should see 4 modules. (discord.js, nodemon, request and ws)
![image](https://user-images.githubusercontent.com/25404381/51335052-6474f280-1a81-11e9-9dd8-a0e8ec6cdfe2.png)

**Comment by ahmadalhamid** [comment]
I got this
![image](https://user-images.githubusercontent.com/35183023/51340070-4b267300-1a8e-11e9-8b32-0f5bd7caad52.png)

**Comment by kennethrisa** [comment]
That's seems correct, what version of node and OS you running?
node --version

**Comment by ahmadalhamid** [comment]
![image](https://user-images.githubusercontent.com/35183023/51340707-ea983580-1a8f-11e9-8c25-489f63066476.png)

**Comment by ahmadalhamid** [comment]
Windows

**Comment by kennethrisa** [comment]
Can you send me the startup command you are trying and a screenshot, i dont see what file/command you did on the first image.

**Comment by ahmadalhamid** [comment]
Like this?
![image](https://user-images.githubusercontent.com/35183023/51340786-292df000-1a90-11e9-93b5-6940744689a0.png)

**Comment by kennethrisa** [comment]
No, the command you are doing for starting the app. how are you starting the app?

**Comment by ahmadalhamid** [comment]
node .

**Comment by kennethrisa** [comment]
try: node app.js , and send me a screenshot of that

**Comment by ahmadalhamid** [comment]
I did try and it is the same
![image](https://user-images.githubusercontent.com/35183023/51341174-fd5f3a00-1a90-11e9-8ee9-f3e435346ddd.png)

**Comment by kennethrisa** [comment]
You cant start the node application trough visual studio code.
Please open a clean powershell and start it from there.

**Comment by ahmadalhamid** [comment]
![image](https://user-images.githubusercontent.com/35183023/51341833-8f1b7700-1a92-11e9-9b0a-0d9b892b4c6a.png)

**Comment by ahmadalhamid** [comment]
I opened power shell  in the folder and that what i got

**Comment by ahmadalhamid** [comment]
I did these as well
![image](https://user-images.githubusercontent.com/35183023/51341877-a65a6480-1a92-11e9-9785-f45c9915247b.png)

**Comment by ahmadalhamid** [comment]
But by node installSVC.js it gave me this error
![image](https://user-images.githubusercontent.com/35183023/51341920-c558f680-1a92-11e9-941d-0745020de48b.png)

**Comment by ahmadalhamid** [comment]
or maybe this has nothing to do, but still did not work

**Comment by kennethrisa** [comment]
im not sure, i can only reproduce the same issue when starting it from vscode.

Try a clean install with a new folder.

**Comment by ahmadalhamid** [comment]
Okay i will try

**Comment by kennethrisa** [comment]
try: npm install --production
npm start

If not, try installing nodejs version 10.15.0 LTS

**Comment by kennethrisa** [comment]
And have you tried run powershell as Administrator?

**Comment by ahmadalhamid** [comment]
no..

**Comment by ahmadalhamid** [comment]
Wait it worked

**Comment by ahmadalhamid** [comment]
Yes it is working. 
It was as you said, i should run it from powershell

**Comment by ahmadalhamid** [comment]
Just installed (npm install -  npm install discord.js request ws), wrote token, API and then started it.
I guess it was that i mixed it with the Windows only instruction.

**Comment by ahmadalhamid** [comment]
Thank you for your time! 
and sorry if i bothered you.

Thanks
