### ISSUE TITLE
Wrong population number

### ISSUE THREAD

**Issue by ahmadalhamid** [kennethrisa/discord-rustserverstatus#20]
This is what the bot shows
![2](https://user-images.githubusercontent.com/35183023/51396044-8a140180-1b3e-11e9-8a3b-398f3337462a.PNG)
and this is the real number
![3](https://user-images.githubusercontent.com/35183023/51396045-8a140180-1b3e-11e9-8c32-eefdc03c0998.PNG)

it is also not the same, comparing it with rust server list and other sites.

**Comment by kennethrisa** [comment]
This is not an issue with bot.
It gets playercount from rest api on following sites and updates it every 3 min.
If they are caching or the bot gets a timeout request, it will not update, and it can be up to 6 min old status. those sites dont ping your server every min, usually every 5 min, so data is not realtime at all.
![image](https://user-images.githubusercontent.com/25404381/51396366-41107d00-1b3f-11e9-9747-823f4eae00f0.png)

**Comment by ahmadalhamid** [comment]
Okay, i just figured it out.
Thank you for the fast reply
