### ISSUE TITLE
Add support for multiple bots

### ISSUE THREAD

**Issue by kennethrisa** [kennethrisa/discord-rustserverstatus#21]
Add support for multiple bots

**Comment by RustyBae** [comment]
kennethrisa, any luck? ive attempted to run from a single desktop as multiple services, but 1 stays active and rest start/stop instantly

**Comment by RustyBae** [comment]
> kennethrisa, any luck? ive attempted to run from a single desktop as multiple services, but 1 stays active and rest start/stop instantly

** Im an idiot, didnt edit the installSVC.js with another name :3 thanks for a great bot! **

**Comment by kennethrisa** [comment]
Done in version v1
