### ISSUE TITLE
Last part not working.

### ISSUE THREAD

**Issue by DuckyLaz** [kennethrisa/discord-rustserverstatus#53]
So ive done the config and all and done all these thins into the power shell;
 npm install
npm install -g node-windows
npm link node-windows
node installSVC.js

they all worked. bot is in my server and I tried to command for it to come online and I get an error message saying this;
Unhandled promise rejection: Error [TokenInvalid]: An invalid token was provided.
    at Client.login (C:\Users\poind\Desktop\discord-rustserverstatus-master\node_modules\discord.js\src\client\Client.js:214:52)
    at C:\Users\poind\Desktop\discord-rustserverstatus-master\app.js:213:16
    at FSReqCallback.oncomplete (node:fs:192:23) {
  code: 'TokenInvalid'
}
So I copied the code straight from the bot. Dont know what else I need to do for the bot to come online?

Someone please help. Also;

If I dont see this please reach out to me aswell on discord: † Laz.#0001

-Laz

**Comment by kennethrisa** [comment]
Hi, you have provided wrong BOT token in the config file. Verify the token and try again.

you can generate a BOT token under: https://discord.com/developers/applications/<BOTNAME> -> BOT -> Token.
